// Bundles dev.html + css/ + js/ into ONE self-contained index.html,
// so the game works no matter how the files are opened or copied.
// Run:  node tools/build.js
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
let html = fs.readFileSync(path.join(root, 'dev.html'), 'utf8');
html = html.replace(/<link rel="stylesheet" href="(css\/[^"]+)" \/>/g, (_, f) => `<style>\n${fs.readFileSync(path.join(root, f), 'utf8')}\n</style>`);
html = html.replace(/<script src="(js\/[^"]+)"><\/script>/g, (_, f) => `<script>\n${fs.readFileSync(path.join(root, f), 'utf8').replace(/<\/script/gi, '<\\/script')}\n</script>`);
html = html.replace('<head>', '<head>\n  <!-- GENERATED by tools/build.js from dev.html, css/ and js/. Edit those files, then rebuild. -->');
fs.writeFileSync(path.join(root, 'index.html'), html);
console.log(`index.html built (${Math.round(html.length / 1024)} KB)`);
